version: '3.8'

services:
  rubot:
    build: .
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-moonshotai/kimi-k2:free}
      - CACHE_ENABLED=true
      - CACHE_MAX_AGE_HOURS=24
      - DOCLING_OCR_ENGINE=${DOCLING_OCR_ENGINE:-easyocr}
      - DOCLING_MODEL_CACHE_DIR=/app/models
      - HF_HOME=/app/models
      - TORCH_HOME=/app/models
      - PYTHONWARNINGS=ignore::UserWarning
    volumes:
      - ./cache:/app/cache
      - ./output:/app/output
      - ./models:/app/models  # Persist model cache
    command: ["--date", "2024-01-15", "--output", "/app/output/result.json", "--verbose"]

  rubot-dev:
    build: 
      context: .
      target: dev
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-moonshotai/kimi-k2:free}
      - DOCLING_OCR_ENGINE=${DOCLING_OCR_ENGINE:-easyocr}
      - DOCLING_MODEL_CACHE_DIR=/app/models
      - HF_HOME=/app/models
      - TORCH_HOME=/app/models
      - PYTHONWARNINGS=ignore::UserWarning
    volumes:
      - .:/app
      - ./cache:/app/cache
      - ./models:/app/models  # Persist model cache
    working_dir: /app
    command: ["bash"]
    stdin_open: true
    tty: true